# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - scaled_joint_trajectory_controller

  scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - cs63_shoulder_pan_joint
      - cs63_shoulder_lift_joint
      - cs63_elbow_joint
      - cs63_wrist_1_joint
      - cs63_wrist_2_joint
      - cs63_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true