controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mobile_base_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
      right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]

      wheel_separation: 0.6
      wheel_radius: 0.1

      use_stamped_vel: false

      # Velocity and acceleration limits
      linear:
        x:
          has_velocity_limits: true
          max_velocity: 1.0
          min_velocity: -1.0
          has_acceleration_limits: true
          max_acceleration: 1.0
          min_acceleration: -1.0
      angular:
        z:
          has_velocity_limits: true
          max_velocity: 1.0
          min_velocity: -1.0
          has_acceleration_limits: true
          max_acceleration: 1.0
          min_acceleration: -1.0 